import type { ConfigContext, ExpoConfig } from "expo/config";

/**
 * DayFlow Mobile runs as an Expo Development Build (not Expo Go): native modules such as
 * expo-notifications today and the iOS Screen Time module later need their own native project.
 * Native folders are generated by `expo prebuild` (Continuous Native Generation) and not committed.
 */
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "DayFlow",
  slug: "dayflow",
  scheme: "dayflow",
  version: "0.1.0",
  platforms: ["ios", "android"],
  // Settings > 화면 모드 chooses system / light / dark at runtime.
  userInterfaceStyle: "automatic",
  orientation: "portrait",
  backgroundColor: "#fff8fb",
  ios: {
    bundleIdentifier: "app.dayflow.mobile",
    supportsTablet: false,
    // Needed to sign the Screen Time extension target (targets/). Set locally, e.g. APPLE_TEAM_ID=ABCDE12345.
    ...(process.env.APPLE_TEAM_ID ? { appleTeamId: process.env.APPLE_TEAM_ID } : {}),
  },
  android: {
    package: "app.dayflow.mobile",
  },
    extra: {
    ...config.extra,
    eas: {
      projectId: "94328509-c66a-4d83-b9a0-8298e42298d9",
    },
  },
  plugins: [
    "expo-router",
    // Local notifications only; no push credentials are needed for Event reminders (NOTI-001).
    ["expo-notifications", { color: "#ee749d" }],
    "@react-native-community/datetimepicker",
    "expo-system-ui",
    // AUTH-004: refresh token in the Keychain / Keystore; Google login in the system browser.
    "expo-secure-store",
    "expo-web-browser",
    // iOS Focus (Screen Time POC): Family Controls entitlement for the app, and the DeviceActivityMonitor extension
    // generated from targets/ on every prebuild.
    "./modules/dayflow-screen-time/app.plugin.js",
    "@bacons/apple-targets",
  ],
});